spring:
    datasource:
        url: jdbc:mysql://mysql-standalone:3306/login?useSSL=false
        username: root
        password: root

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 251136527939-lhp488if4770q38loo56u5abfh97gm1n.apps.googleusercontent.com
              clientSecret: 4nuudq9gCMtT9Tb71BCgCcuT
              redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
  sms:
    apiKey: KC5bi9XhFUf72NYyPeGdHr6SjR8VLutmpgvaOxkoc1Ew4nlI3TmWqfcv9YKARSQpwINaVgxj0MFusOiB
    senderId: FSTSMS
    smsTemplate: Your OTP for signing in is ABC